### PR TITLE
Fix issue WP-API/OAuth1#59, OAuth callback isn't called

### PR DESCRIPTION
**Pull request by sblaz**

### CODE REVIEW

**Comment by coderkevin** [comment]
I had an issue with this. I had to do a rawurldecode() on the callback before saving it to make this work.

**Comment by sblaz** [comment]
Hmm, indeed, I think this patch applied by itself is insufficient to get the callback working. I also had some issues with double-encoding of the oauth_callback parameter value. Applied #65 and then removed the two rawurlencode() calls in join_with_equals_sign() and was good to go. The url decoding stuff all seems to happen earlier in normalize_parameters()

**Comment by coderkevin** [comment]
In my case, normalize_parameters() is really messing up my already partially encoded parameters, so by removing normalize_parameters() instead, I was able to keep the rawurldecode() calls.

See: #91

I have created a PR which merges your changes with AlexC's and removes normalize_parameters() in favor of encoding them in the join_with_equals_sign() function: #92

**Comment by rmccue** [comment]
Thanks for the PR!

This is [already applied](https://github.com/WP-API/OAuth1/blob/f8fa82dcf328bfe752b24c6fde1f6fd9a56ae7a5/lib/class-wp-json-authentication-oauth1-authorize.php#L73-L83) in a separate spot; is this not working for you?

**Comment by rmccue** [comment]
Closing out; this should be fixed, and in any case, this PR no longer applies as a lot of the code has been rewritten. Thanks anyway!

**Pull request closed without merging**
