### PR TITLE
Add admin UI

### PR DESCRIPTION
**Pull request by rmccue**
This is still an early first pass and requires fleshing out in some important respects (cannot currently revoke tokens, e.g.).

* [x] Add consumers
* [x] Edit consumers
* [ ] Delete consumers
* [ ] Add UI for out-of-band callbacks (see #28)
* [x] List current tokens for a user
* [x] Revoke an access token

### CODE REVIEW

**Comment by rachelbaker** [comment]
@rmccue New OAuth Clients Application fields are not being saved.  
To reproduce:
1. Visit Users -> Applications (wp-admin/users.php?page=json-oauth).
2. Click `Add New`
3. Enter the Consumer Name and Description.
4. Click the `Add Consumer` button.
5. Note that the Consumer Name and Description are "Undefined"

**Comment by kosso** [comment]
I've been using this code to provide a simple Admin UI for 'API Clients' which has been working fine for me. 

https://github.com/italy-portugal/OAuth1/commit/786c12bbaedeba43645ee6a2f063018fe9d81d7d

Here's a [screenshot](https://github.com/italy-portugal/OAuth1/commit/786c12bbaedeba43645ee6a2f063018fe9d81d7d#diff-43698e13ff8b1ecb651c0af006aee52a)

**Comment by rmccue** [comment]
This has been sitting unmerged for far too long; merging now, and will fix afterwards.

**Comment by kosso** [comment]
Just tried this on a fresh beta nightly 4.4-beta4-35724 : 

After adding a new consumer, it takes you directly into the edit page for that app (which itself seems a bit weird, as I expected to go back to the apps list). 

I can see the client json_consumer post was created and its key and secret was generated in the wp_postmeta table, but the client and secret are not being displayed on the client edit page (which is why I assume you're redirecting to the edit page after an add. To copy/paste the key/secret to an app).

**Pull request merged**
